"""
SARPack — logbook/exporter.py
Export compiled and rendered ICS forms as:
  1. ZIP packet — all 8 PDFs bundled for email submission to PEMA/county EOC
  2. JSON export — structured data for future e-filing systems
  3. Individual PDF — single form download
"""

import io
import json
import zipfile
import logging
from datetime import datetime, timezone

log = logging.getLogger("logbook.exporter")

FORM_FILENAMES = {
    "ics_201": "ICS-201_Incident_Briefing.pdf",
    "ics_204": "ICS-204_Assignment_List.pdf",
    "ics_205": "ICS-205_Radio_Plan.pdf",
    "ics_206": "ICS-206_Medical_Plan.pdf",
    "ics_209": "ICS-209_Status_Summary.pdf",
    "ics_211": "ICS-211_CheckIn_List.pdf",
    "ics_214": "ICS-214_Activity_Log.pdf",
    "ics_215": "ICS-215_Operational_Planning.pdf",
}


def build_zip_packet(incident_number: str, rendered_forms: dict[str, bytes]) -> bytes:
    """
    Bundle all rendered PDFs into a ZIP file.
    Returns ZIP bytes ready to stream as a download.

    Args:
        incident_number: Used in the ZIP filename and manifest
        rendered_forms:  {form_key: pdf_bytes} from generator.render_all()
    """
    buf = io.BytesIO()

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # Add each PDF
        for form_key, pdf_bytes in rendered_forms.items():
            filename = FORM_FILENAMES.get(form_key, f"{form_key}.pdf")
            zf.writestr(filename, pdf_bytes)
            log.debug("Added %s to zip (%d bytes)", filename, len(pdf_bytes))

        # Add a manifest
        manifest = {
            "incident_number": incident_number,
            "generated_at":    datetime.now(timezone.utc).isoformat(),
            "forms_included":  list(rendered_forms.keys()),
            "file_count":      len(rendered_forms),
            "note": (
                "This packet was generated by SARPack — Unified Rescue Operations Platform. "
                "All forms are signed by the Incident Commander and ready for agency submission."
            ),
        }
        zf.writestr(
            "MANIFEST.json",
            json.dumps(manifest, indent=2),
        )

    log.info("Built ZIP packet for %s: %d forms", incident_number, len(rendered_forms))
    return buf.getvalue()


def build_json_export(compiled: dict) -> bytes:
    """
    Export the full compiled form data as structured JSON.
    Strips binary fields and normalizes for e-filing.
    Returns UTF-8 encoded JSON bytes.
    """
    # Deep copy and clean for export
    export = {
        "sarpack_export_version": "1.0",
        "generated_at":           datetime.now(timezone.utc).isoformat(),
        "incident": {
            "id":             compiled["incident"].get("id"),
            "number":         compiled["incident"].get("incident_number"),
            "name":           compiled["incident"].get("incident_name"),
            "type":           compiled["incident"].get("incident_type"),
            "status":         compiled["incident"].get("status"),
            "started_at":     compiled["incident"].get("started_at"),
            "closed_at":      compiled["incident"].get("closed_at"),
            "county":         compiled["incident"].get("county"),
            "state":          compiled["incident"].get("state"),
            "lat":            compiled["incident"].get("lat"),
            "lng":            compiled["incident"].get("lng"),
        },
        "commander": {
            "name":  _person_name(compiled.get("commander")),
            "phone": compiled["commander"].get("phone","") if compiled.get("commander") else "",
        },
        "forms": {
            "ics_201": compiled.get("ics_201", {}),
            "ics_204": compiled.get("ics_204", []),
            "ics_205": compiled.get("ics_205", {}),
            "ics_206": compiled.get("ics_206", {}),
            "ics_209": compiled.get("ics_209", {}),
            "ics_211": compiled.get("ics_211", {}),
            "ics_214": compiled.get("ics_214", []),
            "ics_215": compiled.get("ics_215", {}),
        },
        "statistics": {
            "total_personnel":  len(compiled.get("deployments", [])),
            "total_segments":   len(compiled.get("segments", [])),
            "total_radio_entries": len(compiled.get("radio_log", [])),
        },
    }

    return json.dumps(export, indent=2, default=str).encode("utf-8")


def zip_filename(incident_number: str) -> str:
    """Generate the ZIP download filename."""
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M")
    safe = incident_number.replace("/", "-").replace(" ", "_")
    return f"SARPack_{safe}_{ts}_ICS_Packet.zip"


def json_filename(incident_number: str) -> str:
    """Generate the JSON download filename."""
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M")
    safe = incident_number.replace("/", "-").replace(" ", "_")
    return f"SARPack_{safe}_{ts}_export.json"


def _person_name(person: dict | None) -> str:
    if not person:
        return ""
    return f"{person.get('first_name','')} {person.get('last_name','')}".strip()
